### ISSUE TITLE
Proteção dos parametros na query

### ISSUE THREAD

**Issue by diegonogueira** [skeleton-elixir/skeleton_query#2]
Caso não faça match com nada, irá retornar tudo. Como proteger?

## 1 - Protected fields

Passar Query.all(query, [:id, :name])

## 2 - Retornar vazio quando não tiver params fazendo matching

Passar Query.all(query, all: true)

Query.all(all: true) == []
Query.all(all: false) == [%{}, %{}]

##  - [MELHOR] 3 Proteger parametros via controller

Igual no rails, fazer um permit no controller. 
Criar funções com matches. 
ou
https://hexdocs.pm/params/readme.html

**Comment by jhonathas** [comment]
Vale a pena dar uma olhada nesse modelo.

https://medium.com/@alves.lcs/phoenix-strong-params-9db4bd9f56d8
https://medium.com/@rockneurotiko/nice-post-42f9191c25f3
https://gist.github.com/rockneurotiko/c30c43b4a3485034037663e83094fb6e
